language: go

go:
  - 1.7.x
  - 1.8.x

services:
  - mysql

script:
  - go get -u github.com/Masterminds/glide
  - glide install
  - tests/runner.sh

notifications:
  email:
    on_success: change
    on_failure: change
